
#- name: create node-exporter directory
#  file: 
#   path: /Node 
#   state: directory

#- name: create prometheus directory
#  file: 
#   path: /Prometheus 
#   state: directory

#- name: create prometheus storage directory 
#  file:
#   path: /var/lib/prometheus
#   state: directory 

- name: install prometheus
  unarchive: 
   src: https://github.com/prometheus/prometheus/releases/download/v1.1.3/prometheus-1.1.3.linux-amd64.tar.gz
   dest: /Prometheus
   copy: no
   validate_certs: False

- name: install node-exporter
  unarchive:
   src: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
   dest: /Node
   copy: no  
   validate_certs: False

- name: create user prometheus
  shell: useradd --no-create-home --shell /bin/false prometheus 

- name: create user node_exporter
  shell: useradd --no-create-home --shell /bin/false node_exporter

- name: add node exporter init service
  copy:
   src: node_exporter.service
   dest: /etc/systemd/system/node_exporter.service
  notify:
   - enable node exporter on boot

- name: config prometheus
  copy:
   src: prometheus.yml
   dest: /Prometheus/prometheus.yml

- name: add prometheus init service
  copy:
   src: prometheus.service
   dest:  /etc/systemd/system/prometheus.service
  notify:
   - enable prometheus service on boot
   
- name: create alertmanager directory
  file: 
   path: /Alertmanager
   state: directory

- name: install alertmanager
  unarchive:
   src: https://github.com/prometheus/alertmanager/releases/download/v0.13.0/alertmanager-0.13.0.linux-amd64.tar.gz
   dest: /Alertmanager
   copy: no
   validate_certs: False


- name: config alertmanager 
  copy:
   src: alertmanager_config.yml
   dest: /Prometheus/alertmanager_config.yml

- name: add alertmanager init service
  copy:
   src: alertmanager.service
   dest: /etc/systemd/system/alertmanager.service 
  notify:
   - enable alertmanager service on boot
 
