
- name: create node-exporter directory
  file: 
   path: /Node 
   state: directory

- name: create prometheus directory
  file: 
   path: /Prometheus 
   state: directory


- name: install prometheus
  unarchive: 
   src: https://github.com/prometheus/prometheus/releases/download/v1.1.3/prometheus-1.1.3.linux-amd64.tar.gz
   dest: /Prometheus
   copy: no

- name: install node-exporter
  unarchive:
   src: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
   dest: /Node
   copy: no  

#- name: create user prometheus
#  shell: useradd --no-create-home --shell /bin/false node_exporter 

#- name: create user node_exporter
#  shell: useradd --no-create-home --shell /bin/false node_exporter

- name: add node exporter init service
  copy:
   src: ./files/node_exporter.service
   dest: /etc/systemd/system/node_exporter.service
  notify:
   - enable node exporter

- name: update prometheus configuration
  copy:
   src: ./files/prometheus.yml
   dest: /Prometheus/prometheus.yml

- name: add prometheus init service
  copy:
   src: ./files/prometheus.service
   dest:  /etc/systemd/system/prometheus.service
  notify:
   - enable prometheus service on boot

- name: run prometheus
  shell: ./prometheus -storage.local.memory-chunks=10000
  args:
   chdir: /Prometheus 
