- name: install prometheus
  unarchive: 
   src: https://github.com/prometheus/prometheus/releases/download/v1.1.3/prometheus-1.1.3.linux-amd64.tar.gz
   dest: /Prometheus
   copy: no

- name: install node-exporter
  unarchive:
   src: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
   dest: /Prometheus
   
- name: run node exporter as a service
  copy:
    src: ../files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  notify:
    - reload systemd
    - enable node exporter service
    - start node exporter service  

- name: update prometheus configuration
  copy:
    src: ../files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: 0644
  notify:
    - run prometheus
