- name: run prometheus
  shell: ./prometheus -storage.local.memory-chunks=10000
  args:
   chdir: /Prometheus

- name: enable node exporter
  systemd:
    name: node_exporter.service
    state: started
    daemon_reload: yes
    enabled: yes

- name: enable prometheus service on boot
  systemd:
    name: prometheus.service
    state: started
    daemon_reload: yes
    enabled: yes

