- name: run prometheus
  shell: ./prometheus -storage.local.memory-chunks=10000
  args:
   chdir: /Prometheus

- name: reload systemd
  shell: systemctl daemon-reload

- name: enable node exporter service
  shell: systemctl enable node_exporter.service

- name: start node exporter service 
  shell: systemctl start node_exporter.service
